### ISSUE TITLE
Adopt built-in fetch

### ISSUE THREAD

**Issue by bterlson** [microsoft/kiota-typescript#1083]
The current approach of using `node-fetch` is less than ideal because it introduces a fair bit of friction in real projects (especially module related 😁) and is big and slow, and Node has built-in fetch in Node 18+ that works a lot better. It also allows sharing more code between browser and node, which is a win.

**Comment by sebastienlevert** [comment]
Now that we have bumped out Node version to at least 18 IIRC (maybe even 20 @baywet) I think we could consider this. This would help with bundle size and standardization of the API.

Any objection on the topic @baywet or @koros?

**Comment by baywet** [comment]
Node18 still has [security support until April 2025](https://endoflife.date/nodejs), so I think targeting node 18/20 for the GA makes sense.
[The fetch API in node is only stable with 21](https://blog.logrocket.com/fetch-api-node-js/) but has been [enabled by default since node18](https://nodejs.org/api/globals.html#fetch) and the API surface from node18 is all I believe we need.

**Comment by baywet** [comment]
Additionally we are still on node-fetch 2.X because it's the last version that supports commonjs modules. See discussions ongoing in #1055.
Removing that dependency will make it easier to both:
- keep supporting commonjs
- drop support for commonjs
