### ISSUE TITLE
Cannot read properties of null (reading 'map')

### ISSUE THREAD

**Issue by illunix** [microsoft/kiota-typescript#1151]
I use [v1.13.0](https://github.com/microsoft/kiota/releases/tag/v1.13.0)
Can someone help me resolve this, somehow Kiota can't handle null values
![image](https://github.com/microsoft/kiota/assets/42069493/656bd3e9-5304-499d-8f09-1cbd6268b232)
![image](https://github.com/microsoft/kiota/assets/42069493/52975354-3d87-4000-8ab1-d3640d2615c4)

**Comment by baywet** [comment]
Hi @illunix 
Thanks for the additional information.
This is caused by a lack of defensive check here.
https://github.com/microsoft/kiota-typescript/blob/8c76a375bfab29d66e7ebe186f71342a1a2a4f54/packages/serialization/json/src/jsonParseNode.ts#L53

Would you be willing to submit a pull request to address this issue?

**Comment by baywet** [comment]
more something like
```ts
if(!Array.isArray(this._jsonNode)) return undefined;
```

**Comment by SrRickGrimes** [comment]
same issue here. 
I am getting this exception:

TypeError: Cannot read properties of null (reading 'map')
    at JsonParseNode.getCollectionOfPrimitiveValues
