### ISSUE TITLE
Angular DEPTH_ZERO_SELF_SIGNED_CERT error when sending request

### ISSUE THREAD

**Issue by illunix** [microsoft/kiota-typescript#1443]
```ts
@Injectable({ providedIn: 'root' })
export class TestApi {
  private _adapter = new FetchRequestAdapter(new BearerTokenAuthProvider());

  public client: TestApiClientGenerated;

  public constructor(@Inject(APP_CONFIG) appConfig: AppConfig) {
    this._adapter.baseUrl = appConfig.baseURL;
    this.client = createTestApiClientGenerated(this._adapter);
  }
}
```

I don't get any error when my adapter looks like this
```ts
  private _adapter = new FetchRequestAdapter(
    new BearerTokenAuthProvider(),
    undefined,
    undefined,
    KiotaClientFactory.create(window.fetch.bind(window))
  );
```

Problem is that I can't use window because I use Angular SSR, what should I do?

**Comment by baywet** [comment]
Hi @illunix 
Thank you for using kiota and for reaching out.

This is a bit strange since effectively `window.fetch === fetch` in the browser. On node, it's [defined globally](https://nodejs.org/api/globals.html#fetch). And [the handler initializes with the global object by default](https://github.com/microsoft/kiota-typescript/blob/e8b88a36faa320d7cb40984fd645a7efecb07586/packages/http/fetch/src/middlewares/browser/middlewareFactory.ts#L27)

I have no experience with Angular SSR but I suspect they are doing something "special" to transfer caching, context, etc... of the requests from the server to the client. [A quick look to their documentation seems to elude to that](https://angular.dev/guide/ssr#authoring-server-compatible-components). And my guess is that you need to pass an instance of a "special HTTP client" built for that purpose.

Let us know if you have any additional comments or questions.
