### ISSUE TITLE
`uri-template-lite` breaks when using a bundler

### ISSUE THREAD

**Issue by andreaTP** [microsoft/kiota-typescript#584]
Trying to use `kiota-typescript` from a UI application that is bundled using `vite` we have been experiencing issues with `uri-template-lite`.

![unnamed](https://user-images.githubusercontent.com/5792097/228851079-d3a2d18e-4955-4a05-a292-5913209f0bca.png)

The current workaround is to exclude the package from the bundler:

```
  build: {
    ...
    rollupOptions: {
      external: ['uri-template-lite'],
    }
  },
```

but is less than ideal and it compromises the "getting started" experience.

We have various options here:
- include the single source of `uri-template-lite` in this codebase
- rely on a different library (that better plays with modules etc.)
- open to other ideas!

**Comment by baywet** [comment]
Thanks for reporting this. 4th option, PR them so this dependency supports that scenario as well.
Especially since there are a number of [RedHat projects that depend on it](https://github.com/litejs/uri-template-lite/network/dependents).
Do you think you could get somebody, or yourself to fix that aspect?
