### ISSUE TITLE
How to include my bearer token to every request that my client make in typescript?

### ISSUE THREAD

**Issue by illunix** [microsoft/kiota-typescript#654]
Hey I try to make middleware or something to make my client add bearer auth header to every request, how can  i do it?

**Comment by baywet** [comment]
Hi @illunix 
Thanks for the question and sorry about the delayed answer here.
The authentication is a separate concept and is not implemented through a middleware handler in Kiota. This is because there are a number of advanced scenarios where one might need to have the "abstract request" contain all the information.
This is also done this way to require people setting up the authentication properly as they setup their client.
There are a number of [authentication providers](https://github.com/search?q=repo%3Amicrosoft%2Fkiota-typescript%20authenticationprovider&type=code) already available for typescript and if you can't find one that fits your scenario, simply reimplement the interface :)
